---
- hosts: client
  become: yes
  tasks:
    - name: install paquets
      apt: name="{{ item }}" state=present
      with_items:
          - lxc
          - lxctl
          - openvswitch-common
          - openvswitch-switch





