---
- hosts: client
  gather_facts: false
  become: true
  vars_files:
   - vars.yml

  tasks:
  - name: Start a container
    lxc_container:
     name: "{{ item.key }}"
     state: stopped
    with_dict: "{{ ctn }}"


